### ISSUE TITLE
Feature request: Ability to center rules text and flavor text on cards like Prosperity

### ISSUE THREAD

**Issue by HelixVita** [MrTeferi/MTG-Proxyshop#30]
![image](https://user-images.githubusercontent.com/102387379/189731396-d6d94827-3755-4cf5-86ba-e4e7bdc90e5b.png)

**Comment by HelixVita** [comment]
Incidentally, this card also exemplifies two other issues:
1. https://github.com/MrTeferi/MTG-Proxyshop/issues/24
2. https://github.com/MrTeferi/MTG-Proxyshop/issues/25

**Comment by MrTeferi** [comment]
I've switched this to "enhancement" label since its not technically a bug, and I will mark the topic complete when the enhancement is finished and 1.2.0 is release.

- In 1.2.0 `is_centered` will be a property you can control, Prosperity will need a slight tweak to the centered ruleset to allow it to be centered when flavor text is present.
- In 1.2.0 I also plan to add a toggle for centering the flavor text.

**Comment by HelixVita** [comment]
> I've switched this to "enhancement" label since its not technically a bug, and I will mark the topic complete when the enhancement is finished and 1.2.0 is release.
> 
> * In 1.2.0 `is_centered` will be a property you can control, Prosperity will need a slight tweak to the centered ruleset to allow it to be centered when flavor text is present.
> * In 1.2.0 I also plan to add a toggle for centering the flavor text.

Sounds great! 👍 Thanks again!

**Comment by MrTeferi** [comment]
I'm going to go ahead and close this issue as this behavior is possible now, just change the centered property of your template to use rules that allow for flavor text 👍 

![image](https://user-images.githubusercontent.com/92750180/223719286-8f8788bf-f975-404f-8032-03ef7fa3c055.png)

Don't let the comment fool you, this applies to the entire text including flavor text, you just have to remove the if case that checks for flavor text being present
