### ISSUE TITLE
Feature request: Save File as PSD in out folder

### ISSUE THREAD

**Issue by pozzum** [MrTeferi/MTG-Proxyshop#35]
This can probably be a config only option to keep menu size down but having a way to save named PSD copies of files would help with a lot of processes I'm working on at the moment.

**Comment by lmancini** [comment]
I might propose a PR for this, which would also strip away any invisible layer in order to save on the final PSD size. Would @MrTeferi consider this for inclusion?

**Comment by lmancini** [comment]
@MrTeferi @pozzum I have a prototype version in my working copy. Quick request for feedback before I open a PR:

 * How you feel about this feature also strip away invisible layers? I think it's the best thing to do because you're saving the result of the render process. If you wanted to make something else visible, you would do it as part of the automation, not manually in the output PSD.

 * What do you think about having this as the **default**, and save a JPEG only if "JPEG Saving" is enabled in the menu? Right now the default is saving to PNG but I think this is seldom used in practice. Some time ago in the Discord @HelixVita even commented that "JPG makes the most sense in most cases" (https://discord.com/channels/889831317066358815/953423615091683368/1025142571535704205).

**Comment by MrTeferi** [comment]
This feature has been committed to main and will be in v1.2.0, Save.JPEG has been replaced with "Output.Filetype", by default set to jpg, other acceptable options are png and psd, anything else will be corrected to jpg automatically (more will be supported in the future)

**Comment by lmancini** [comment]
@MrTeferi uhm ok, my implementation actually went one step further and also stripped away invisible layers, but yes I guess this could be part of my plugin `post_execute` step, as it's not something everybody would want (I actually also added an extra step of merging all raster layers together in order to save on space). Ping me if you still want to have a look, if not I'll just add this in my plugin.

**Comment by MrTeferi** [comment]
> @MrTeferi uhm ok, my implementation actually went one step further and also stripped away invisible layers, but yes I guess this could be part of my plugin `post_execute` step, as it's not something everybody would want (I actually also added an extra step of merging all raster layers together in order to save on space). Ping me if you still want to have a look, if not I'll just add this in my plugin.

Yeah the problem I see with clearing all the hidden layers or flattening/merging layers is this kinda defeats the purpose of saving as PSD in the first place, I mean a user who wants this really out there feature would almost certainly wanna preserve the layer structure in its entirety so they can manually modify the document right? At least that would be my assumption haha

**Comment by pozzum** [comment]
My use case has been that it is easier to go back and adjust the art and also the text.

With some promotional art you have white border that you don't necessarily need to trim if you zoom in the full art more.

Alternate name cards become easier if you just have to go back and edit the text name without having to do a full custom card.

I specifically had the use case of printing red & black borders - with paper & original card wording.  I also wanted this for silver border card adjustments where having the pinlines/border/background being merged is not exactly an issue,  However for these I did just delete all hidden layers and that went a long way to trimming the PSD file size.

**Comment by HelixVita** [comment]
> However for these I did just delete all hidden layers and that went a long way to trimming the PSD file size.

This. 

I think saving as PSD will be used for a lot more reasons than just the ability to “change your mind” and unhide previously hidden layers. 

Personally I’d be mainly interested in it for making post-render adjustments to art position and color correction. 

Thing is: Yes, storage comes cheap these days, but PSDs do take up a surprising amount of space. If you’ve got hundreds of PSDs, then  deleting all the layers you know you’re not gonna use will make a serious difference.

**Comment by lmancini** [comment]
> then deleting all the layers you know you’re not gonna use will make a serious difference.

@HelixVita earlier today @MrTeferi merged this PR of mine (https://github.com/MrTeferi/MTG-Proxyshop/pull/55) which includes a useful function to iterate on layers: in the PR description I include an example of precisely how to delete invisible layers.

In my initial implementation this was the default behaviour of saving to PSD, but the same effect can be achieved if you call that function in the `post_text_layers` hook (as I'm doing in my plugin).
