### ISSUE TITLE
[BUG] - Hybrid mana creatures throw error while enabling layers

### ISSUE THREAD

**Issue by lukegothic** [MrTeferi/MTG-Proxyshop#60]
**Describe the bug**
When proxyshop tries to render a Hybrid creature card, it throws the error below. Hybrid non-creature cards do work.
EDIT: It does work with normal template, and it fails on women's day template.

**To Reproduce**
1. Put image called Deathrite Shaman inside art folder
2. Open proxyshop
4. Select women's day template
5. Press render all

**Your system:**
 - Python version: 3.10.4
 - Windows version: W10
 - Photoshop version: 2021
 - Proxyshop version: 1.1.9

**Screenshots**

![image](https://user-images.githubusercontent.com/3224037/208857609-a3bc10c5-6e6c-4f9f-bcaf-28d2974ad447.png)
![image](https://user-images.githubusercontent.com/3224037/208857698-a7b71167-6cd8-4d5a-9a00-15df136c1f20.png)

**Comment by lukegothic** [comment]
Delving into what layers proxyshop enables to create a hybrid creature card, it enables the PT Box layer of "Land", which is missing on showcase. Is correct that proxyshop enables this PT Box layer instead of the multicolor one?

**Comment by MrTeferi** [comment]
This is a limitation of the Women's day template, at the time it was created hybrid cards and creature lands had never been done in the full art secret lair border (colloquially called Women's Day cuz that was the first Secret Lair it showed up in), not sure if any have been done since then. Hybrid cards have the same color PT box as land creatures.

I do have this one working on hybrid cards for me on my system, I duplicated the colorless PT and named it "Land", not sure if I had to do anything else its been a few weeks. In any case there's going to be a round of template updates for 1.2.0 so stay tuned!
