### ISSUE TITLE
[BUG] - Italics Issue with some 40K cards

### ISSUE THREAD

**Issue by nprez** [MrTeferi/MTG-Proxyshop#61]
The cards Necron Deathmark and Chaos Defiler from 40K don't properly italicize their ability words

Windows 10
Photoshop 2021

**Comment by MrTeferi** [comment]
> The cards Necron Deathmark and Chaos Defiler from 40K don't properly italicize their ability words
> 
> Windows 10 Photoshop 2021

This bug was reported some time back and has already been patched for 1.2.0 which is due to release today so no worries!

In the future please use the issue template provided on Github as your windows version and Photoshop version may not be enough information to properly identify the cause for some issues. Thanks!
