### ISSUE TITLE
[BUG] - [RuntimeError] Unable to install project dependencies (kivy):

### ISSUE THREAD

**Issue by davidianstyle** [MrTeferi/MTG-Proxyshop#65]
**Describe the bug**
Unable to install project dependencies (kivy):

`Hash for kivy (2.2.0.dev0) from archive Kivy-2.2.0.dev0-cp311-cp311-win_amd64.whl not found in known hashes`

![Settings - MTG-Proxyshop - Visual Studio Code 1_27_2023 12_35_50 PM](https://user-images.githubusercontent.com/6446624/215156053-eae101ee-b880-49c1-8cc3-93d46ed217dd.png)

**To Reproduce**
1. `poetry install`
2. Receive `RuntimeError` while installing `kivy` (2.2.0.dev0)

**Your system:**
 - Python version: Python 3.11.1
 - Windows version: Microsoft Windows 10 Pro (Version 10.0.19045 Build 19045)
 - Photoshop version: Photoshop 2023 (Version 24.1.1)

**Screenshots**

**Comment by davidianstyle** [comment]
Implemented the same workaround outlined in #57 within the poetry virtual environment:

![Settings - MTG-Proxyshop - Visual Studio Code 1_27_2023 12_48_39 PM](https://user-images.githubusercontent.com/6446624/215159393-84d82df0-b5b4-471e-855c-b42fe31b7708.png)

1. `$ poetry env use python`
2. `$ poetry shell`
3. `$ python --version` (to confirm python version)
4. `$ python -m pip install kivy --pre --no-deps --index-url  https://kivy.org/downloads/simple/`
5. `$ python -m pip install "kivy[base]" --pre --extra-index-url https://kivy.org/downloads/simple/`
6. `$ python main.py` (to confirm app loads)
7. `$ exit` (exit virtual env)

Going forward, running `$ poetry run python main.py` works fine after installation dependencies resolved.

**Comment by MrTeferi** [comment]
That's weird because I tested the current configuration as working for 3.11 a week ago and worked perfectly, they must have borked up 3.11 support again on the development branch. Really annoying that it's now been nearly a year since a new official Kivy release and last I heard in December the next version is "a ways away".

In any case I won't be addressing this issue with any further PR's as long term the plan now is to move away from Kivy to use Electron as the GUI! I'll leave this issue open so it can instruct others how to run the current Proxyshop on 3.11 👍

**Comment by MrTeferi** [comment]
Kivy 2.2.0 has officially released and has full support for Python 3.11, I'll be updating the Kivy dependency in the next round of commits! This issue is now **FIXED** 👍
