### ISSUE TITLE
[BUG] - Unable to insert collector info

### ISSUE THREAD

**Issue by nprez** [MrTeferi/MTG-Proxyshop#71]
**Describe the bug**
Error on rendering Chandra, Torch of Defiance. "Unable to insert collector info"

Logs:
============================================================================
> 03/22/2023 23:55
============================================================================
  File "src\templates.py", line 907, in execute
  File "src\templates.py", line 435, in collector_info
  File "src\templates.py", line 479, in collector_info_authentic
  File "src\helpers.py", line 1219, in replace_text
  File "photoshop\api\application.py", line 354, in executeAction
  File "comtypes\client\lazybind.py", line 182, in caller
  File "comtypes\automation.py", line 745, in _invoke
  Reason: (-2147023170, 'The remote procedure call failed.', (None, None, None, 0, None))

**To Reproduce**
1. Use MTG Art Downloader to grab the art of Chandra, Torch of Defiance off of mtgpics.
2.  Attempt to render the card using Proxyshop 1.6.0

**Your system:**
 - Python version: 3.10.6
 - Windows version: Windows 10
 - Photoshop version: 2021

**Screenshots**
![image](https://user-images.githubusercontent.com/18358103/227099325-c4705de2-ddd0-4545-9306-4122e42babac.png)

**Comment by nprez** [comment]
Additional info:

Sometimes, instead I will get the error "Unable to load artwork" for the same card.

The logs then read:
============================================================================
> 03/23/2023 00:02
============================================================================
  File "src\templates.py", line 901, in execute
  File "src\templates.py", line 755, in load_artwork
  File "src\templates.py", line 166, in art_layer
  File "src\helpers.py", line 66, in getLayer
  File "photoshop\api\_core.py", line 66, in __getattribute__
  File "photoshop\api\application.py", line 62, in activeDocument
  File "comtypes\client\lazybind.py", line 168, in __getattr__
  File "comtypes\automation.py", line 745, in _invoke
  Reason: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))

**Comment by MrTeferi** [comment]
The first one happens because your Photoshop doesn't like targeted replacement (would probably be fixed by updating to latest Photoshop which seems to have addressed the issue in my case). To remedy the issue without updating change "Targeted Text Replacement" to Off in Proxyshop settings. It will increase execution time by a couple tenths of a second but should prevent that crash! 👍 

The second log isn't a bug, RPC (remote procedure call) server unavailable pretty much always means Photoshop is not responding to script communication, can usually be fixed by just restarting Photoshop/Proxyshop/both, sometimes might have to restart Windows if the RPC server has crashed completely . This can happen on unstable Photoshop installations or if a previous crash happened that locked up/crashed the RPC server.  Its not very common but its a Windows/Photoshop idiosyncrasy that can happen on occasion. It might also happen if Photoshop is busy (a dialog box is open for example), but I think the error log would say something different if that were the case.

**Comment by MrTeferi** [comment]
> Thanks, turning targeted text replacement off seems to have fixed the error, though now for some reason I need to have Photoshop already open prior to the whole process or it will crash when it tries to open after I click Render All.
> 
> I've had bad experiences before trying to get 2022 to work. Haven't checked to see if there's a crack available for 2023 yet. Totally understand the frustration of having people with outdated versions of Photoshop complain, though I'm not about to pay Adobe $21/month for a side hobby of mine haha.

I would use this method to get the latest, I think its the most stable option available by far! Wish you luck :)
https://www.reddit.com/r/GenP/wiki/redditgenpguides/#wiki_guide_.232_-_dummy_guide_for_first_timers_genp_.28method_1.3A_cc.2Bgenp.29
