### ISSUE TITLE
extended art planeswalker template won't render

### ISSUE THREAD

**Issue by hathwellcrisping** [MrTeferi/MTG-Proxyshop#75]
File "src\templates.py", line 910, in run_tasks
  File "src\templates.py", line 2581, in enable_frame_layers
  File "src\helpers.py", line 1571, in content_fill_empty_area
  File "photoshop\api\_selection.py", line 62, in expand
  File "comtypes\client\lazybind.py", line 182, in caller
  File "comtypes\automation.py", line 745, in _invoke
  Reason: (-2147213497, None, (None, None, None, 0, None))

![ps error](https://github.com/MrTeferi/MTG-Proxyshop/assets/20904473/d9ec242c-d59d-453f-b5d6-255cb937949a)

**Comment by MrTeferi** [comment]
So I had one other person encounter this issue (though it seemed to resolve itself oddly enough), but I dug into it pretty extensively and came up with nothing, the template is testing clean from Proxyshop v1.6.0 all the way to the unreleased 1.9.0, using both my local PW Extended template and the version that is live on the updater (last update was on January 31st). I recommend checking the updater to see if an update for that template is available, or manually downloading `pw-extended.psd` from the google drive linked on the Github page/README and overwriting it in your templates folder to see if that helps.

That said, I will be modifying the content aware fill function to prevent this issue from occurring in the theoretical future by checking that a selection has been made before the expand action is called. I left it alone in the past because it was a good red flag for seeing when a template's reference box isn't set up correctly, but might be best to just patch it altogether and have it just print a warning in the python environment console instead!

**Comment by MrTeferi** [comment]
As promised content aware fill was overhauled in 1.9.0, this "bug" can't occur anymore. In the future please make sure to tell us your Proxyshop version among other details when submitting a bug report or seeking help. Closing this 👍
